### ISSUE TITLE
дизайн шаблонов

### ISSUE THREAD

**Issue by Dinara-Dulanova** [art-invite/inv1#11]
- [x] 1 шаблон
- [x] 2 шаблон
- [ ]

**Comment by agkondakov91** [comment]
реф текста — https://easytoinvite.ru/text
ещё реф — https://einvite.ru/

**Comment by spiridovichp** [comment]
![image](https://github.com/user-attachments/assets/f6d55a35-7b47-4d6d-8ad9-1f3b48df3d7f)

**Comment by spiridovichp** [comment]
![image](https://github.com/user-attachments/assets/d0381466-2aff-4a43-98e5-2eed3e339392)

**Comment by spiridovichp** [comment]
![image](https://github.com/user-attachments/assets/debea944-e580-4196-9e45-fa0d783f7b7f)

**Comment by spiridovichp** [comment]
![image](https://github.com/user-attachments/assets/99ce288f-b9fe-4ec1-b34c-d06e64accf2a)

**Comment by agkondakov91** [comment]
1 макет (дизайн)

https://clck.ru/3E39rG

**Comment by agkondakov91** [comment]
2 макет (дизайн)

https://clck.ru/3E5DbY
